### ISSUE TITLE
test

### ISSUE THREAD

**Issue by anjalimish** [anjalimish/Angular-Calculator-App#4]
Description of the issue:
The infinite loading once we click on submit button on "My Page"

Intended outcome:
The infinite loading on the profile should get resolved.

## Todo @anjalimish 

- [x] Fix the issue on the local system
- [x] Do unit test
- [x] If it is working as expected on the local system, push it to the dev branch with appropriate comments & commit messages and test it.
- [x] Let another developer review the code
- [x] If it is working as expected on the dev branch, create PR from the dev branch and merge it to the staging branch and test it.
- [x] If it is working as expected on the staging environment, create PR from the staging branch and merge it to production.
(check with the Manager before merging to production)
